// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spring/options/service.proto
// Protobuf Java Version: 4.30.2

package com.a67793581.spring.options;

public final class Service {
  private Service() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      Service.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(com.a67793581.spring.options.Service.springOption);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int SPRING_OPTION_FIELD_NUMBER = 60000;
  /**
   * <code>extend .google.protobuf.ServiceOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.ServiceOptions,
      com.a67793581.spring.options.SpringOption> springOption = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.a67793581.spring.options.SpringOption.class,
        com.a67793581.spring.options.SpringOption.getDefaultInstance());
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spring_options_SpringOption_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spring_options_SpringOption_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034spring/options/service.proto\022\016spring.o" +
      "ptions\032 google/protobuf/descriptor.proto" +
      "\"\'\n\014SpringOption\022\027\n\007is_flux\030\001 \001(\010R\006isFlu" +
      "x:g\n\rspring_option\022\037.google.protobuf.Ser" +
      "viceOptions\030\340\324\003 \001(\0132\034.spring.options.Spr" +
      "ingOptionR\014springOption\210\001\001Be\n\034com.a67793" +
      "581.spring.optionsP\001ZCgithub.com/a677935" +
      "81/proto-spring-plugin/gen/spring/option" +
      "s;optionsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    internal_static_spring_options_SpringOption_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_spring_options_SpringOption_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spring_options_SpringOption_descriptor,
        new java.lang.String[] { "IsFlux", });
    springOption.internalInit(descriptor.getExtensions().get(0));
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
