// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spring/options/service.proto
// Protobuf Java Version: 4.30.2

package com.a67793581.spring.options;

public interface SpringOptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:spring.options.SpringOption)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool is_flux = 1 [json_name = "isFlux"];</code>
   * @return The isFlux.
   */
  boolean getIsFlux();
}
