// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spring/options/service.proto
// Protobuf Java Version: 4.30.2

package com.a67793581.spring.options;

/**
 * Protobuf type {@code spring.options.SpringOption}
 */
public final class SpringOption extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:spring.options.SpringOption)
    SpringOptionOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      SpringOption.class.getName());
  }
  // Use SpringOption.newBuilder() to construct.
  private SpringOption(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SpringOption() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.a67793581.spring.options.Service.internal_static_spring_options_SpringOption_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.a67793581.spring.options.Service.internal_static_spring_options_SpringOption_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.a67793581.spring.options.SpringOption.class, com.a67793581.spring.options.SpringOption.Builder.class);
  }

  public static final int IS_FLUX_FIELD_NUMBER = 1;
  private boolean isFlux_ = false;
  /**
   * <code>bool is_flux = 1 [json_name = "isFlux"];</code>
   * @return The isFlux.
   */
  @java.lang.Override
  public boolean getIsFlux() {
    return isFlux_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (isFlux_ != false) {
      output.writeBool(1, isFlux_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (isFlux_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, isFlux_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.a67793581.spring.options.SpringOption)) {
      return super.equals(obj);
    }
    com.a67793581.spring.options.SpringOption other = (com.a67793581.spring.options.SpringOption) obj;

    if (getIsFlux()
        != other.getIsFlux()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IS_FLUX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsFlux());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.a67793581.spring.options.SpringOption parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.a67793581.spring.options.SpringOption parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.a67793581.spring.options.SpringOption parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.a67793581.spring.options.SpringOption parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.a67793581.spring.options.SpringOption parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.a67793581.spring.options.SpringOption parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.a67793581.spring.options.SpringOption parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.a67793581.spring.options.SpringOption parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.a67793581.spring.options.SpringOption parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.a67793581.spring.options.SpringOption parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.a67793581.spring.options.SpringOption parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.a67793581.spring.options.SpringOption parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.a67793581.spring.options.SpringOption prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code spring.options.SpringOption}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:spring.options.SpringOption)
      com.a67793581.spring.options.SpringOptionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.a67793581.spring.options.Service.internal_static_spring_options_SpringOption_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.a67793581.spring.options.Service.internal_static_spring_options_SpringOption_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.a67793581.spring.options.SpringOption.class, com.a67793581.spring.options.SpringOption.Builder.class);
    }

    // Construct using com.a67793581.spring.options.SpringOption.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      isFlux_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.a67793581.spring.options.Service.internal_static_spring_options_SpringOption_descriptor;
    }

    @java.lang.Override
    public com.a67793581.spring.options.SpringOption getDefaultInstanceForType() {
      return com.a67793581.spring.options.SpringOption.getDefaultInstance();
    }

    @java.lang.Override
    public com.a67793581.spring.options.SpringOption build() {
      com.a67793581.spring.options.SpringOption result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.a67793581.spring.options.SpringOption buildPartial() {
      com.a67793581.spring.options.SpringOption result = new com.a67793581.spring.options.SpringOption(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.a67793581.spring.options.SpringOption result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.isFlux_ = isFlux_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.a67793581.spring.options.SpringOption) {
        return mergeFrom((com.a67793581.spring.options.SpringOption)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.a67793581.spring.options.SpringOption other) {
      if (other == com.a67793581.spring.options.SpringOption.getDefaultInstance()) return this;
      if (other.getIsFlux() != false) {
        setIsFlux(other.getIsFlux());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              isFlux_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean isFlux_ ;
    /**
     * <code>bool is_flux = 1 [json_name = "isFlux"];</code>
     * @return The isFlux.
     */
    @java.lang.Override
    public boolean getIsFlux() {
      return isFlux_;
    }
    /**
     * <code>bool is_flux = 1 [json_name = "isFlux"];</code>
     * @param value The isFlux to set.
     * @return This builder for chaining.
     */
    public Builder setIsFlux(boolean value) {

      isFlux_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_flux = 1 [json_name = "isFlux"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIsFlux() {
      bitField0_ = (bitField0_ & ~0x00000001);
      isFlux_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:spring.options.SpringOption)
  }

  // @@protoc_insertion_point(class_scope:spring.options.SpringOption)
  private static final com.a67793581.spring.options.SpringOption DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.a67793581.spring.options.SpringOption();
  }

  public static com.a67793581.spring.options.SpringOption getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SpringOption>
      PARSER = new com.google.protobuf.AbstractParser<SpringOption>() {
    @java.lang.Override
    public SpringOption parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SpringOption> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SpringOption> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.a67793581.spring.options.SpringOption getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

